# Generated by Django 5.1.2 on 2024-11-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apt_num",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_num",
            field=models.CharField(max_length=10),
        ),
    ]
