# Generated by Django 5.1.3 on 2024-12-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wine",
            old_name="designation",
            new_name="region",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="description",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="name",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="wine_review",
        ),
        migrations.AddField(
            model_name="wine",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="subregion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="vintage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
