# Generated by Django 5.1.3 on 2024-12-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_designation_wine_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupWine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wine", models.CharField(max_length=255)),
                ("winery", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("varietal", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "appellation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("alcohol", models.FloatField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("reviewer", models.CharField(blank=True, max_length=255, null=True)),
                ("review", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="wine",
            name="age",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="country",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="region",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="subregion",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="vintage",
        ),
        migrations.AddField(
            model_name="wine",
            name="name",
            field=models.CharField(default="Unknown Wine", max_length=200),
        ),
        migrations.AddField(
            model_name="wine",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="reviewer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
