# Generated by Django 5.1.3 on 2024-12-09 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_lookupwine_remove_wine_age_remove_wine_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 12, 9, 1, 8, 8, 863541, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
