# Generated by Django 5.1.3 on 2024-12-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_wine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
