# Generated by Django 5.1.3 on 2024-12-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_review_image_url_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="body_rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="review",
            name="finish_rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="review",
            name="taste_rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5),
        ),
    ]
