# Generated by Django 5.1.2 on 2024-12-09 02:57

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_review_body_rating_review_finish_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="wine",
        ),
        migrations.AddField(
            model_name="review",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="varietal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="wine_name",
            field=models.CharField(default="Wine Name", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="winery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="body_rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="finish_rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="taste_rating",
            field=models.IntegerField(),
        ),
    ]
