# Generated by Django 5.1.2 on 2024-12-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_remove_review_price_remove_review_varietal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="varietal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
