# Generated by Django 5.1.2 on 2024-12-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_review_varietal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="varietal",
        ),
    ]
