# Generated by Django 5.1.2 on 2024-12-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_remove_review_varietal"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="varietal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
