# Generated by Django 5.1.2 on 2024-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_delete_wineranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="restaurant_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
