# Generated by Django 5.1.2 on 2024-12-10 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_review_latitude_review_longitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="triedwine",
            name="user",
        ),
        migrations.RemoveField(
            model_name="triedwine",
            name="wine",
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="project.wine",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "wine")},
            },
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
        migrations.DeleteModel(
            name="TriedWine",
        ),
    ]
