# Generated by Django 5.1.2 on 2024-10-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0004_friends"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Friends",
            new_name="Friend",
        ),
    ]
